# Generated by Django 4.2.28 on 2026-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text="Transcribed text from employee's voice")),
                ('detected_intent', models.CharField(max_length=50)),
                ('response_text', models.TextField(help_text='Generated HR response')),
                ('audio_file', models.CharField(blank=True, default='', help_text='Relative path to the TTS audio file', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversation Log',
                'verbose_name_plural': 'Conversation Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
