# Generated by Django 4.2.28 on 2026-02-25 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
