# Generated by Django 4.2.28 on 2026-02-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
